# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='type',
            field=models.CharField(choices=[('photo', 'PHOTO'), ('drawing', 'DRAWING'), ('video', 'VIDEO'), ('post', 'POST')], default='POST', max_length=7),
        ),
    ]
