# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20171019_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='post',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='video',
            name='entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='entry',
            name='vid_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Title'),
        ),
        migrations.DeleteModel(
            name='Drawing',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
