# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20171020_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.TextField(blank=True, null=True, verbose_name='Tags (comma separated)'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='vid_link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Video Link (optional)'),
        ),
    ]
