# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20171020_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tags',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Tags (comma separated)'),
        ),
    ]
