# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-20 06:49
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20171020_0548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='vid_link',
        ),
        migrations.AddField(
            model_name='entry',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Video Link (optional)'),
        ),
    ]
