# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20171020_0649'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='img_thumb',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='thumbs', verbose_name='Image Thumbnail'),
        ),
    ]
