# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_auto_20171117_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='entryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Embedded Post Image'),
        ),
    ]
