# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 22:03
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_auto_20171117_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text_body',
            field=markdownx.models.MarkdownxField(blank=True, null=True, verbose_name='Body Text'),
        ),
    ]
