# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_auto_20171117_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='StationSearchTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=9)),
                ('search_radius', models.DecimalField(decimal_places=4, max_digits=9)),
            ],
        ),
    ]
