# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_stationsearchtarget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsearchtarget',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Target Latitude [decimal degrees]'),
        ),
        migrations.AlterField(
            model_name='stationsearchtarget',
            name='lon',
            field=models.DecimalField(decimal_places=4, max_digits=9, verbose_name='Target Lontigude [decimal degrees]'),
        ),
        migrations.AlterField(
            model_name='stationsearchtarget',
            name='search_radius',
            field=models.DecimalField(choices=[('1km', 1.0), ('5km', 5.0), ('10km', 10.0)], decimal_places=1, default='1km', max_digits=3, verbose_name='Search Radius [km]'),
        ),
    ]
