# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_auto_20171214_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climatestation',
            name='period_of_record',
        ),
        migrations.AddField(
            model_name='climatestation',
            name='end_year',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Record End Year'),
        ),
        migrations.AddField(
            model_name='climatestation',
            name='start_year',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Record Start Year'),
        ),
    ]
