# Generated by Django 2.0 on 2018-01-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkht', '0002_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
