# Generated by Django 2.0 on 2018-01-02 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkht', '0004_auto_20180102_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationsearchtarget',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180)], verbose_name='Target Latitude [decimal degrees]'),
        ),
        migrations.AlterField(
            model_name='stationsearchtarget',
            name='lon',
            field=models.DecimalField(decimal_places=4, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='Target Lontigude [decimal degrees]'),
        ),
    ]
