# Generated by Django 2.0 on 2018-01-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dkht', '0006_auto_20180103_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='type',
        ),
        migrations.AddField(
            model_name='entry',
            name='post_type',
            field=models.CharField(choices=[('project', 'PROJECT')], default='PROJECT', max_length=7),
        ),
        migrations.AlterField(
            model_name='stationsearchtarget',
            name='search_radius',
            field=models.DecimalField(choices=[(5.0, '5km'), (10.0, '10km'), (25.0, '25km'), (50.0, '50km')], decimal_places=1, default='1km', max_digits=3, verbose_name='Search Radius [km]'),
        ),
    ]
